//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiConsentimientos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsentimientoInformado
    {
        public DateTime fecha { get; set; }
        public TimeSpan hora { get; set; }
        public string lugar { get; set; }
        public string tipoIdPaciente { get; set; }
        public int numeroIdPaciente { get; set; }
        public string tipoIdProfesional { get; set; }
        public int numeroIdProfesional { get; set; }
        public int codigoProcedimiento { get; set; }
        public byte[] huellaPacienteImg { get; set; }
        public byte[] firmaPaciente { get; set; }
        public byte[] huellaProfesionalImg { get; set; }
        public byte[] firmaProfesional { get; set; }
        public byte[] huellaTutorImg { get; set; }
        public byte[] firmaTutor { get; set; }
        public string procedimiento { get; set; }
    }
}
