//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiConsentimientos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        public string tipoId { get; set; }
        public int numeroId { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public byte[] firma { get; set; }
        public byte[] huella { get; set; }
        public byte[] huellaImg { get; set; }
        public string tipoIdTutor { get; set; }
        public int numeroIdTutor { get; set; }
        public string nombreTutor { get; set; }
        public string parentescoTutor { get; set; }
        public byte[] firmaTutor { get; set; }
        public byte[] huellaTutor { get; set; }
        public byte[] huellaTutorImg { get; set; }
    }
}
